
SELECT CEILING(12.333223)

SELECT FLOOR(12.333223)

SELECT RAND(0)

SELECT ROUND(12.33323323, 2)

SELECT * FROM [ITENS NOTAS FISCAIS]

SELECT [QUANTIDADE], [PREÇO], ROUND(([QUANTIDADE] * [PREÇO]),2) FROM [ITENS NOTAS FISCAIS]

SELECT YEAR(DATA)  AS ANO, FLOOR(SUM(IMPOSTO * (QUANTIDADE * PREÇO))) AS TOTAL
FROM [NOTAS FISCAIS] NF 
INNER JOIN [ITENS NOTAS FISCAIS] INF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(DATA) = 2016
GROUP BY YEAR(DATA) ;