
DECLARE @NOME VARCHAR(200)
DECLARE CURSOR1 CURSOR FOR SELECT TOP 4 NOME FROM [TABELA DE CLIENTES]
OPEN CURSOR1
FETCH NEXT FROM CURSOR1 INTO @NOME
WHILE @@FETCH_STATUS = 0
BEGIN
   PRINT @NOME
   FETCH NEXT FROM CURSOR1 INTO @NOME
END

-- Crie um script usando um cursor para achar o valor total de todos os créditos de todos os clientes.


DECLARE @LIMITECREDITO FLOAT
DECLARE @LIMITECREDITOACUM FLOAT
DECLARE CURSOR1 CURSOR FOR SELECT [LIMITE DE CREDITO] 
    FROM [TABELA DE CLIENTES]
SET @LIMITECREDITOACUM = 0
OPEN CURSOR1
FETCH NEXT FROM CURSOR1 INTO @LIMITECREDITO
WHILE @@FETCH_STATUS = 0
BEGIN
    SET @LIMITECREDITOACUM = @LIMITECREDITOACUM + 
        @LIMITECREDITO
    FETCH NEXT FROM CURSOR1 INTO @LIMITECREDITO
END
CLOSE CURSOR1
DEALLOCATE CURSOR1
PRINT @LIMITECREDITOACUM


DECLARE @NOME VARCHAR(10)
DECLARE CURSOR5 CURSOR FOR
SELECT [NOME] FROM [TABELA DE CLIENTES];

OPEN CURSOR5;
FETCH NEXT FROM CURSOR5 INTO @NOME;
FETCH NEXT FROM CURSOR5 INTO @NOME;
FETCH NEXT FROM CURSOR5 INTO @NOME;
FETCH NEXT FROM CURSOR5 INTO @NOME;

WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT @NOME
	FETCH NEXT FROM CURSOR5 INTO @NOME;

END
CLOSE CURSOR5;
DEALLOCATE CURSOR5;
