DECLARE @NOME VARCHAR(10)
SET @NOME = 'João';

DECLARE @IDADE INT 
SET @IDADE = 10;

DECLARE @DATA_NASCIMENTO DATE
SET @DATA_NASCIMENTO = '20070110';

DECLARE @CUSTO INT
SET @CUSTO = 10.23;

PRINT @NOME
PRINT @IDADE
PRINT @DATA_NASCIMENTO
PRINT @CUSTO

DECLARE @NUMNOTAS INT
SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
    WHERE DATA = '20170101'
PRINT @NUMNOTAS


IF OBJECT_ID('TABELA_TESTE', 'U') IS NOT NULL
	DROP TABLE TABELA_TESTE
IF OBJECT_ID('TABELA_TESTE', 'U') IS NOT NULL
CREATE TABLE TABELA_TESTE(ID VARCHAR(10))


SELECT GETDATE()
SELECT DATENAME(WEEKDAY, GETDATE()) -- RETORNA O MOME DA SEMANA EM UMA DATA EX. QUARTA, 30-09-2020


SELECT DATENAME(WEEKDAY, DATEADD(DAY,6,GETDATE())) -- PEGAR UMA DATA PRA FRENTE

DECLARE @DIA_SEMANA VARCHAR(20)
DECLARE @NUMERO_DIAS INT 

SET @NUMERO_DIAS = 3
SET @DIA_SEMANA = DATENAME(WEEKDAY,DATEADD(DAY, @NUMERO_DIAS, GETDATE()))
PRINT @DIA_SEMANA
IF @DIA_SEMANA = 'DOMINGO' OR @DIA_SEMANA = 'Sábado'
	PRINT 'ESTE DIA É FIM DE SEMANA'
ELSE
	PRINT 'ESTE DIA É DIA DA SEMANA'