SELECT * FROM [TABELA DE PRODUTOS] WHERE [NOME DO PRODUTO] LIKE '%Litros%' and [sabor]=	'laranja';


SELECT * FROM [TABELA DE CLIENTES] WHERE [NOME] LIKE '%Mattos';

SELECT DISTINCT* FROM [TABELA DE PRODUTOS];



SELECT DISTINCT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS];


SELECT DISTINCT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS] WHERE [SABOR]='Laranja';

SELECT DISTINCT EMBALAGEM, TAMANHO, SABOR FROM [TABELA DE PRODUTOS];

SELECT DISTINCT BAIRRO FROM [TABELA DE CLIENTES];

SELECT DISTINCT BAIRRO FROM [TABELA DE CLIENTES]
WHERE CIDADE = 'RIO DE JANEIRO';

SELECT  BAIRRO FROM [TABELA DE CLIENTES];

SELECT TOP 10 * FROM [NOTAS FISCAIS] WHERE [DATA] = '2017-01-01';

SELECT * FROM [TABELA DE PRODUTOS] WHERE [NOME DO PRODUTO] = 'Linha Refrescante - 1 Litro - Morango/Limão';

SELECT DISTINCT [QUANTIDADE]  FROM [ITENS NOTAS FISCAIS] WHERE [CODIGO DO PRODUTO] = 1101035 ORDER BY QUANTIDADE DESC;

SELECT [NOME DO PRODUTO], SUM([PREÇO DE LISTA])FROM [TABELA DE PRODUTOS] GROUP BY [NOME DO PRODUTO];


SELECT [NOME DO PRODUTO], SUM([PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS] GROUP BY [NOME DO PRODUTO], [PREÇO DE LISTA];


SELECT COUNT(*)  AS TOTAL FROM [ITENS NOTAS FISCAIS] WHERE [CODIGO DO PRODUTO] = 1101035 AND QUANTIDADE = 99;